name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.1"
          - "3.2"
          - "3.3"
        gemfile:
          - rails6.1
          - rails7.0
          - rails7.1
          - rails7.2
          - resque_1_and_redis_4

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: zendesk/checkout@v4

      - uses: zendesk/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - run: bundle exec rake test

  tests_successful:
    name: Tests passing?
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if ${{ needs.tests.result == 'success' }}
          then
            echo "All tests pass"
          else
            echo "Some tests failed"
            false
          fi
