name: Publish Gem

on:
  push:
    branches: main
    paths: lib/resque/durable/version.rb
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    environment: rubygems-publish
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
      - name: Install dependencies
        run: bundle install
      - uses: rubygems/release-gem@v1
